server:
  port: 8081
  servlet:
    context-path: /profile
    
spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:postgresql://localhost:5433/mycare_profile}
    driverClassName: ${DBSM_DRIVER:org.postgresql.Driver}
    username: ${DBMS_USERNAME:postgres}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      dialect: ${Dialect:org.hibernate.dialect.PostgreSQLDialect}
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.mycareportal.event.dto.KafkaMessageSerializer
    topic:
      profile-updated: profile-updated-topic
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
      