server:
  port: 8081
  servlet:
    context-path: /profile
    
spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:postgresql://localhost:5433/mycare_profile}
    driverClassName: ${DBSM_DRIVER:org.postgresql.Driver}
    username: ${DBMS_USERNAME:postgres}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      dialect: ${Dialect:org.hibernate.dialect.PostgreSQLDialect}
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: profile-group
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer  
      properties:
        request.timeout.ms: 10000
        connections.max.idle.ms: 10000
        retry.backoff.ms: 1000
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
      