server:
  port: 8082
  servlet:
    context-path: /doctor

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/mycare_doctor}
    driverClassName: ${DBSM_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      dialect: ${Dialect:org.hibernate.dialect.MySQL8Dialect} 
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: doctor-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        request.timeout.ms: 10000
        connections.max.idle.ms: 10000
        retry.backoff.ms: 1000